[package]
name = "fos-js"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "JavaScript runtime for fOS Engine"

[dependencies]
fos-dom = { path = "../fos-dom" }
tracing.workspace = true
thiserror.workspace = true


