[package]
name = "fos-layout"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Layout engine for fOS Engine"

[dependencies]
tracing.workspace = true
thiserror.workspace = true
